# Configuración del Gateway
# Definir la zona de límite de peticiones (10MB de memoria, 5 peticiones por segundo)
limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/s;

server {
    listen 80;
    server_name www.2026-a064.lat;

    # Máximo tamaño de subida (importante para expedientes PDF/IMÁGENES)
    client_max_body_size 50M;

    # 2. Rutas para Swagger (Documentación) 
    location /api/docs/ {
        proxy_pass http://identity-service:8000/api/docs/;
        include /etc/nginx/conf.d/proxy_params;
    }

    # 3. Rutas para el Schema de OpenAPI - AGREGAR ESTO
    location /api/schema/ {
        proxy_pass http://identity-service:8000/api/schema/;
        include /etc/nginx/conf.d/proxy_params;
    }

    # 1. Rutas para el Identity Microservice (Autenticación)

    

    location /api/auth/ {
        # Comentado hasta que el servicio 'identity-service' exista en docker-compose
        proxy_pass http://identity-service:8000/;
        include /etc/nginx/conf.d/proxy_params;
    }

    # Aplicar límite de velocidad específicamente al login y registro
    location /api/auth/login/ {
        limit_req zone=login_limit burst=10 nodelay;
        proxy_pass http://identity-service:8000/login/;
        include /etc/nginx/conf.d/proxy_params;
    }

    location /api/auth/password-reset/ {
    limit_req zone=login_limit burst=5 nodelay;
    proxy_pass http://identity-service:8000/password-reset/;
    include /etc/nginx/conf.d/proxy_params;
}

    # 2. Rutas para el Mortgage Core (Lógica de Negocio)
    location /api/mortgage/ {
        proxy_pass http://mortgage-core:8001;
        include /etc/nginx/conf.d/proxy_params;
    }

     # Ruta raíz 
    location / {
        proxy_pass http://frontend-spa:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}