# Generated by Django 4.2.28 on 2026-03-02 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('BROKER', 'Bróker'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('status', models.CharField(default='Activo', max_length=50, verbose_name='Estatus')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('marital_status', models.CharField(blank=True, max_length=45, verbose_name='Estado civil')),
                ('curp_rfc', models.CharField(blank=True, max_length=45, verbose_name='CURP/RFC')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('municipality', models.CharField(blank=True, max_length=50, verbose_name='Municipio')),
                ('housing_status', models.CharField(blank=True, max_length=50, verbose_name='Situación vivienda')),
                ('person_type', models.CharField(blank=True, max_length=10, verbose_name='Tipo persona')),
                ('admin_creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Admin alta')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
