# Generated by Django 4.2.29 on 2026-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de Sesión Exitoso'), ('LOGIN_FAILED', 'Intento de Inicio Fallido'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PROFILE_UPDATE', 'Actualización de Perfil'), ('ACCOUNT_ACTIVATION', 'Activación de Cuenta'), ('ACCOUNT_SUSPENSION', 'Suspensión de Cuenta')], max_length=50),
        ),
    ]
