# Generated by Django 4.2.30 on 2026-05-06 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deleted_at_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_load',
            field=models.IntegerField(default=0, verbose_name='Carga actual'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_for_assignments',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_load',
            field=models.IntegerField(default=10, verbose_name='Carga máxima'),
        ),
        migrations.AlterField(
            model_name='user',
            name='housing_status',
            field=models.CharField(choices=[('RENT', 'Renta'), ('OWN', 'Propia'), ('MORTGAGE', 'Hipotecada'), ('OTHER', 'Otro'), ('ANY', 'Cualquiera'), ('NONE', 'Ninguno')], default='RENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación/Oficina'),
        ),
        migrations.CreateModel(
            name='BrokerServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(db_index=True, max_length=10, verbose_name='Código Postal cubierto')),
                ('broker', models.ForeignKey(limit_choices_to={'role': 'BROKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Área de servicio',
                'unique_together': {('broker', 'postal_code')},
            },
        ),
    ]
