# Generated by Django 4.2.30 on 2026-05-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_current_load_user_is_active_for_assignments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerservicearea',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='brokerservicearea',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brokerservicearea',
            name='alcaldia_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Prefijo de Alcaldía'),
        ),
        migrations.AlterField(
            model_name='brokerservicearea',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='brokerservicearea',
            unique_together={('broker', 'alcaldia_prefix')},
        ),
        migrations.RemoveField(
            model_name='brokerservicearea',
            name='postal_code',
        ),
    ]
