services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - mortgage-network
    depends_on:
      - api-gateway

  # Base de datos para el microservicio de Identidad
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - mortgage-network
    ports:
      - "5433:5432" # Mapeo a puerto diferente para evitar conflictos locales

  # Base de datos para el microservicio Core
  core-db:
    image: postgres:15-alpine
    container_name: core-db
    restart: always
    environment:
      POSTGRES_DB: ${CORE_DB_NAME}
      POSTGRES_USER: ${CORE_DB_USER}
      POSTGRES_PASSWORD: ${CORE_DB_PASSWORD}
    volumes:
      - core-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks: 
      - mortgage-network

# --- MICROSERVICIOS ---
  identity-service:
    build: ./identity-service
    container_name: identity-service
    restart: always
    env_file:
      - ./identity-service/.env
    volumes:
      - ./identity-service:/app
    environment:
      - DATABASE_URL=postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0 # conexión a Redis
    depends_on:
      - auth-db
      - redis
    networks:
      - mortgage-network
    command: python manage.py runserver 0.0.0.0:8000 # mantener el contenedor activo


  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - identity-service
      - frontend-spa
      - mortgage-core
    networks:
      - mortgage-network
    restart: always
    

  frontend-spa:
    build: ./frontend-spa
    container_name: frontend-spa
    volumes:
      - ./frontend-spa:/app
      - /app/node_modules # Evita que los nodos locales sobrescriban los del contenedor [cite: 2026-03-05]
    networks:
      - mortgage-network
    environment:
      - VITE_API_URL=https://www.2026-a064.lat/api
    restart: always
    

  # Nuevo servicio para procesar tareas en segundo plano
  celery-worker:
    build: ./identity-service
    container_name: celery-worker
    restart: always
    volumes:
      - ./identity-service:/app
    environment:
      - DATABASE_URL=postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_USER=${EMAIL_USER} # Para el envío de correos
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - auth-db
      - redis
    networks:
      - mortgage-network
    command: celery -A core worker --loglevel=info
    

  intelligence-service:
      build: ./intelligence-service
      container_name: intelligence-service
      ports:
        - "8002:8002"
      networks:
        - mortgage-network
      volumes:
      - ./intelligence-service/app:/app/app
      - ./intelligence-service/models:/app/models
      restart: always

  # Bus de Eventos (Redis)
  redis:
    image: redis:7-alpine
    container_name: redis-bus
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mortgage-network

  mortgage-core:
    build: ./mortgage-core
    container_name: mortgage-core
    volumes:
      - ./mortgage-core:/app
    ports:
      - "8001:8001"
    env_file:
      - .env  
    environment:
      - DATABASE_URL=postgres://${CORE_DB_USER}:${CORE_DB_PASSWORD}@core-db:5432/${CORE_DB_NAME}
      - INTELLIGENCE_SERVICE_URL=http://intelligence-service:8002
    networks:
      - mortgage-network
    depends_on:
      - core-db
      - intelligence-service
    command: python manage.py runserver 0.0.0.0:8001

networks:
  mortgage-network:
    driver: bridge

volumes:
  auth-db-data:
  core-db-data:
  redis-data: