# -*- coding: utf-8 -*-
"""COTIZACION_BANORTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_Fx4KJa_-7VV2pAq_Mhu4ODK8jQ9ADr
"""

# Commented out IPython magic to ensure Python compatibility.
import sys

# =====================================================
# Seccion 1: LIBRERÍAS, CONSTANTES Y HELPERS
# =====================================================
import copy
import pandas as pd
import numpy as np
from datetime import date
from numpy_financial import irr

# -------------------------
# Constantes de idioma
# -------------------------
_DIAS = ['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo']
_MESES = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']

def fecha_es(dt: date) -> str:
    return f"{_DIAS[dt.weekday()]}, {dt.day:02d} de {_MESES[dt.month-1]} de {dt.year}"

def money(x) -> str:
    return f"${x:,.2f}"

def pct(x) -> str:
    return f"{x:.2f}%"

# -------------------------
# Finanzas
# -------------------------
def factor_anualidad(tasa_mensual: float, n: int) -> float:
    if np.isclose(tasa_mensual, 0.0):
        return 1.0 / n
    return (tasa_mensual * (1 + tasa_mensual)**n) / ((1 + tasa_mensual)**n - 1)

def cat_por_tir(credito_banorte, avaluo, gastos_aprob, com_apertura, politicas, mensualidad, plazo):
    """CAT aproximado vía TIR de flujos: t0 = recibido neto, posteriores = mensualidad."""
    incluye_ap = bool(politicas["cat"].get("incluye_apertura_financiada_t0", True))
    if politicas.get("comision_apertura_financiada", True) and not incluye_ap:
        recibido = credito_banorte - (avaluo + gastos_aprob)
    else:
        recibido = credito_banorte - (avaluo + gastos_aprob + com_apertura)
    flujos = [round(recibido,2)] + [-round(mensualidad,2)]*plazo
    tirm = irr(flujos)
    if tirm is None or np.isnan(tirm):
        return np.nan
    return (1 + tirm)**12 - 1

def seguros_y_admin(valor, politicas):
    sa = round(valor * float(politicas["seguros"]["suma_asegurable_pct"]), 2)
    vida_cfg = politicas["seguros"]["vida"]
    if vida_cfg["metodo"] == "pormil":
        seg_vida = round((sa / 1000.0) * float(vida_cfg["tarifa_pormil_mensual"]), 2)
        if not np.isfinite(seg_vida):
            seg_vida = round(vida_cfg.get("monto_mensual_fijo_fallback", 0.0), 2)
    else: # metodo == "fijo"
        seg_vida = round(float(vida_cfg["monto_mensual"]), 2)

    danos_cfg = politicas["seguros"]["danos"]
    if danos_cfg["metodo"] == "fijo":
        seg_danos = round(float(danos_cfg["monto_mensual_iva"]), 2)
    elif danos_cfg["metodo"] == "porcentaje_saldo":
        tasa_anual_danos = float(danos_cfg["tasa_anual"])
        iva_danos = float(danos_cfg["iva"])
        # Assuming the 'valor' here is the property value to calculate the insurance base
        # And assuming this is a monthly calculation. Tasa anual / 12 months.
        seg_danos = round((valor * tasa_anual_danos / 12) * (1 + iva_danos), 2)
    else:
        seg_danos = 0.0  # Fallback for unknown method, or if damages insurance is not applicable

    com_admin = round(float(politicas["comision_admin_mensual"]), 2)
    return sa, seg_vida, seg_danos, com_admin

def avaluo_contra_cfg(valor, pol):
    if "avaluo_monto" in pol:
        return round(float(pol["avaluo_monto"]), 2)
    base = valor * float(pol.get("avaluo_pct_mil", 0.0))
    iva = float(pol.get("avaluo_iva_pct", 0.0))
    if base == 0 and "avaluo_monto" not in pol:
        return 5800.00  # fallback
    return round(base * (1 + iva), 2)

def notariales_contra_cfg(valor, pol):
    not_cfg = pol["notariales"]
    if not_cfg["modo"] == "porcentaje":
        return round(valor * float(not_cfg["pct"]), 2)
    return round(float(not_cfg["monto"]), 2)

def obtener_instituto(usuario, tipo_producto):
    """
    Devuelve (nombre_instituto, credito_inst, subcuenta).

    Reglas:
    - 'fpt'              -> usa bloque FOVISSSTE (crédito + subcuenta).
    - 'cofinavit'        -> usa crédito + subcuenta INFONAVIT.
    - 'cta_infonavit'    -> usa crédito + subcuenta INFONAVIT.
    - 'apoyo'            -> SOLO subcuenta INFONAVIT (SIN crédito vigente).
    - 'tradicional' u otros -> sin instituto.
    """
    if tipo_producto == "fpt":
        fovi = usuario.get("fovissste", {}) or {}
        return (
            "FOVISSSTE",
            float(fovi.get("credito_fovissste", 0.0)),
            float(fovi.get("subcuenta_vivienda", 0.0))
        )

    if tipo_producto in ("cofinavit", "cta_infonavit"):
        info = usuario.get("infonavit", {}) or {}
        return (
            "INFONAVIT",
            float(info.get("credito_infonavit", 0.0)),
            float(info.get("subcuenta_vivienda", 0.0))
        )

    if tipo_producto == "apoyo":
        # Apoyo INFONAVIT: NO hay crédito INFONAVIT activo, solo subcuenta
        info = usuario.get("infonavit", {}) or {}
        return (
            "INFONAVIT",
            0.0,
            float(info.get("subcuenta_vivienda", 0.0))
        )

    # Tradicional u otros sin instituto
    return ("", 0.0, 0.0)



# =====================================================
# Seccion 3: CÁLCULOS BASE (MENSUALIDAD Y TOPES)
# =====================================================

def _mensualidad_total(credito, tasa_anual, plazo, adders, pol, subcuenta=0.0, tipo_producto="tradicional"):
    """
    Mensualidad total = (cap+int) + adders, respetando apertura financiada y
    abatimiento de subcuenta SOLO en 'apoyo'. Redondeo a peso.
    """
    apertura_pct = float(pol["comision_apertura_pct"])
    apertura_fin = bool(pol.get("comision_apertura_financiada", True))
    com_ap = credito * apertura_pct
    principal = credito + (com_ap if apertura_fin else 0.0)

    if tipo_producto == "apoyo":
        aplicar = min(subcuenta, principal)
        principal = max(0.0, principal - aplicar)

    tasa_m = float(tasa_anual) / 12.0
    f = factor_anualidad(tasa_m, plazo)
    cap_int = principal * f
    m_total = cap_int + adders
    return float(np.floor(m_total + 0.5))  # redondeo a peso

def _credito_tope_estructura(valor, enganche, credito_inst, subcuenta, pol, tipo_producto):
    """
    Tope de crédito Banorte por estructura y políticas (aforo Banorte, aforo total, etc.).
    """
    aforo_max_banorte = float(pol.get("aforo_max", 0.95))
    tope_total = pol.get("apoyos", {}).get("aforo_total_max_instituto", None)
    instituto_tiene_credito = bool(pol.get("apoyos", {}).get("instituto_tiene_credito", False)) or (credito_inst > 0)

    # Estructura según tipo
    if tipo_producto == "cofinavit":
        estruct = max(0.0, valor - (enganche + credito_inst + subcuenta))
    elif tipo_producto in ("fpt", "cta_infonavit"):
        estruct = max(0.0, valor - (enganche + credito_inst))
    else:  # tradicional / apoyo
        estruct = max(0.0, valor - enganche)

    credito_top = min(estruct, valor * aforo_max_banorte)

    if tope_total is not None and instituto_tiene_credito:
        # Límite por aforo total (instituto + Banorte)
        credito_top = min(credito_top, max(0.0, valor * float(tope_total) - credito_inst))

    return round(max(0.0, credito_top), 2)

# =====================================================
# Seccion 4: RESCATE MANIPIULACION ENGANCHE
# =====================================================

def rescate_por_enganche(
    valor, enganche_inicial, ingreso_usuario, plazo, pol, tipo_producto,
    credito_inst, subcuenta, tasas_df,
    adders,
    enganche_min_pct, enganche_max_pct=0.30, delta_enganche_pct=0.02,
    tol_mxn=50.0
):
    """
    Aumenta el enganche (>= mínimo del producto) en pasos delta_enganche_pct
    hasta lograr mensualidad <= ingreso/relacion_ir para alguna tasa.

    Parámetros clave:
    - valor: valor de la vivienda
    - enganche_inicial: enganche calculado con el % original del usuario
    - ingreso_usuario: ingreso bruto mensual
    - plazo: plazo en meses
    - pol: diccionario de políticas del producto
    - tipo_producto: 'tradicional', 'apoyo', 'cofinavit', 'cta_infonavit', 'fpt'
    - credito_inst: crédito del instituto (INFONAVIT / FOVISSSTE) si aplica
    - subcuenta: subcuenta de vivienda si aplica
    - tasas_df: DataFrame con columnas:
        - 'nombre_tasa'
        - 'tasa_anual_pct' (en porcentaje, ej. 9.78, no 0.0978)
    - adders: seg_vida + seg_danos + com_admin
    - enganche_min_pct: mínimo % de enganche permitido por el producto (ej. 0.10)
    - enganche_max_pct: máximo % de enganche a considerar en rescate (ej. 0.30)

    Devuelve:
    - (mejor_fila, df_ranking) si encontró algo
    - None si no hay forma de cumplir la capacidad de pago ni aumentando enganche
    """
    # Sanidad básica
    if valor <= 0:
        return None

    relacion_ir = float(pol["relacion_ir"])
    mensualidad_tope = float(ingreso_usuario) / relacion_ir

    # Punto de partida (respetar mínimo de producto)
    pct_usuario = enganche_inicial / valor  # puede venir por debajo del mínimo
    pct_actual = max(pct_usuario, enganche_min_pct)
    pct_actual = min(pct_actual, enganche_max_pct)

    mejores = []
    for _, r in tasas_df.iterrows():
        tasa_nombre = r["nombre_tasa"]
        tasa_anual = r["tasa_anual_pct"] / 100.0

        # Busca el menor % de enganche que cumpla para esta tasa
        pct = pct_actual
        cumple = None
        while pct <= enganche_max_pct + 1e-9:
            enganche = round(valor * pct, 2)
            credito_top = _credito_tope_estructura(
                valor, enganche, credito_inst, subcuenta, pol, tipo_producto
            )
            if credito_top <= 0:
                pct += delta_enganche_pct
                continue

            m = _mensualidad_total(
                credito_top, tasa_anual, plazo, adders, pol,
                subcuenta=subcuenta, tipo_producto=tipo_producto
            )
            if m <= mensualidad_tope + tol_mxn:
                cumple = (pct, enganche, credito_top, m)
                break
            pct += delta_enganche_pct

        if cumple is not None:
            pct_ok, eng_ok, cred_ok, m_ok = cumple
            mejores.append({
                "tasa_nombre": tasa_nombre,
                "tasa_anual_pct": r["tasa_anual_pct"],
                "pct_enganche_nuevo": pct_ok,
                "enganche_nuevo": eng_ok,
                "credito_max": cred_ok,
                "mens_compatible": m_ok
            })

    if not mejores:
        return None

    df = pd.DataFrame(mejores).sort_values(
        by=["mens_compatible", "tasa_anual_pct", "credito_max"],
        ascending=[True, True, False]
    ).reset_index(drop=True)

    return df.iloc[0], df

# =====================================================
# Seccion 5: COTIZAR POR TASA + GENERAR COTIZACIONES
# =====================================================

def _cotizar_por_tasa(producto_cfg, usuario, nombre_tasa, tasa_anual_fija,
                      tol_mxn=50.0):
    """
    Cotiza UNA tasa del producto:
    - Intenta 'Normal' con enganche del usuario (respetando mínimo del producto).
    - Si no cumple I/R, aplica 'Rescate por enganche' SOLO para esta tasa.
    Retorna un dict listo para salidas Usuario/Broker.
    """
    pol = producto_cfg["politicas"]
    tipo = pol.get("tipo")
    valor = float(usuario["valor_vivienda"])
    ingreso = float(usuario["ingreso_bruto"])
    plazo = int(usuario["plazo_meses"])

    # -------------------------
    # Enganche (mínimo producto)
    # -------------------------
    con_instituto = bool(pol.get("apoyos", {}).get("tiene_apoyos", False))
    min_pct_enganche = 0.05 if con_instituto else 0.10
    user_pct_e = float(usuario.get("pct_enganche", min_pct_enganche))

    # Respetar mínimo del producto
    pct_e_usado = max(user_pct_e, min_pct_enganche)
    enganche = round(valor * pct_e_usado, 2)

    if user_pct_e < min_pct_enganche:
        motivo_enganche = (
            f"Enganche ingresado ({user_pct_e*100:.1f}%) "
            f"ajustado al mínimo del producto ({min_pct_enganche*100:.0f}%)."
        )
    elif user_pct_e > min_pct_enganche:
        motivo_enganche = (
            f"Se respetó el enganche ingresado por el usuario ({user_pct_e*100:.1f}%), "
            f"mayor al mínimo requerido ({min_pct_enganche*100:.0f}%)."
        )
    else:
        motivo_enganche = f"Enganche igual al mínimo del producto ({min_pct_enganche*100:.0f}%)."

    # -------------------------
    # Instituto (según tipo)
    # -------------------------
    if tipo == "tradicional":
        nombre_inst, credito_inst, subcuenta = ("", 0.0, 0.0)
    else:
        nombre_inst, credito_inst, subcuenta = obtener_instituto(usuario, tipo)

    instituto_tiene_credito = (
        bool(pol.get("apoyos", {}).get("instituto_tiene_credito", False)) or (credito_inst > 0)
    )

    # -------------------------
    # Crédito preliminar usando _credito_tope_estructura
    # -------------------------
    credito_pre = _credito_tope_estructura(
        valor=valor,
        enganche=enganche,
        credito_inst=credito_inst,
        subcuenta=subcuenta,
        pol=pol,
        tipo_producto=tipo
    )
    credito_pre = max(0.0, round(credito_pre, 2))

    # -------------------------
    # Costos / seguros
    # -------------------------
    avaluo = avaluo_contra_cfg(valor, pol)
    gastos_not = notariales_contra_cfg(valor, pol)
    com_ap_pre = round(credito_pre * float(pol["comision_apertura_pct"]), 2)
    gastos_aprob = round(float(pol["gastos_aprobacion"]), 2)
    sa, seg_vida, seg_danos, com_admin = seguros_y_admin(valor, pol)

    # -------------------------
    # Subcuenta (según tipo)
    # -------------------------
    sub_aplica_capital = 0.0
    descuento_sub_desembolso = 0.0
    if tipo == "apoyo":
        principal_pago_tmp = credito_pre + (com_ap_pre if pol.get("comision_apertura_financiada", True) else 0.0)
        sub_aplica_capital = min(subcuenta, principal_pago_tmp)
    elif tipo in ("cta_infonavit", "fpt"):
        descuento_sub_desembolso = min(subcuenta, enganche)

    desembolso_base = round(enganche + avaluo + gastos_not + gastos_aprob, 2)
    gastos_inst = 0.0
    if tipo == "cofinavit":
        gastos_inst = round(credito_inst * float(pol.get("gastos_infonavit_pct", 0.0)), 2)
        desembolso_base = round(desembolso_base + gastos_inst, 2)
    if tipo == "fpt":
        gastos_inst = round(credito_inst * float(pol.get("gastos_fovissste_pct", 0.0)), 2)
        desembolso_base = round(desembolso_base + gastos_inst, 2)
    desembolso_base = round(max(0.0, desembolso_base - descuento_sub_desembolso), 2)

    # -------------------------
    # Tabla de esta tasa (Normal)
    # -------------------------
    tasa_a = float(tasa_anual_fija)
    tasa_m = tasa_a / 12.0
    f = factor_anualidad(tasa_m, plazo)
    principal_pago_base = credito_pre + (com_ap_pre if pol.get("comision_apertura_financiada", True) else 0.0)
    if tipo == "apoyo":
        principal_pago_base = max(0.0, principal_pago_base - sub_aplica_capital)

    cap_int = round(principal_pago_base * f, 2)
    mensualidad = round(cap_int + seg_vida + seg_danos + com_admin, 2)
    ingreso_req = round(mensualidad * float(pol["relacion_ir"]), 2)
    cat = cat_por_tir(
        credito_banorte=credito_pre,
        avaluo=avaluo,
        gastos_aprob=gastos_aprob,
        com_apertura=com_ap_pre,
        politicas=pol,
        mensualidad=mensualidad,
        plazo=plazo
    )
    cat_pct = (round(cat*100, 1) if pd.notna(cat) else np.nan)

    # -------------------------
    # ¿Cumple "Normal"?
    # -------------------------
    relacion_ir = float(pol["relacion_ir"])
    tope_mens = float(ingreso) / relacion_ir
    if mensualidad <= tope_mens + tol_mxn:
        pago_total_mens = round(mensualidad * plazo, 2)
        costo_total = round(desembolso_base + pago_total_mens, 2)
        aforo_b = (credito_pre / valor) if valor > 0 else 0.0
        aforo_i = (credito_inst / valor) if (valor > 0 and instituto_tiene_credito) else 0.0
        return {
            "modo": "Normal",
            "producto": producto_cfg["nombre"],
            "tasa_nombre": nombre_tasa,
            "tasa_anual_pct": round(tasa_a*100, 2),
            "cat_pct": cat_pct,
            "mensualidad": mensualidad,
            "ingreso_req": ingreso_req,
            "credito_banorte": round(credito_pre, 2),
            "enganche": enganche,
            "pct_enganche": pct_e_usado,
            "desembolso_inicial": desembolso_base,
            "pago_total_mensualidades": pago_total_mens,
            "costo_total_cliente": costo_total,
            "plazo": plazo,
            "valor_vivienda": valor,
            "aforo_banorte_pct": round(aforo_b*100, 2),
            "aforo_instituto_pct": round(aforo_i*100, 2),
            "aforo_total_pct": round((aforo_b+aforo_i)*100, 2),
            "nota_enganche": motivo_enganche,
        }

    # ====================================================
    # Si no cumple Normal → RESCATE POR ENGANCHE
    # ====================================================
    df_tmp = pd.DataFrame([{
        "nombre_tasa": nombre_tasa,
        "tasa_anual_pct": round(tasa_a*100, 2),
        "mensualidad": mensualidad,
        "ingreso_req": ingreso_req,
        "cat": cat_pct
    }])

    out = rescate_por_enganche(
        valor=valor,
        enganche_inicial=enganche,
        ingreso_usuario=ingreso,
        plazo=plazo,
        pol=pol,
        tipo_producto=tipo,
        credito_inst=credito_inst,
        subcuenta=subcuenta,
        tasas_df=df_tmp,
        adders=seg_vida + seg_danos + com_admin,
        enganche_min_pct=min_pct_enganche,
        enganche_max_pct=0.30,
        delta_enganche_pct=0.02,
        tol_mxn=tol_mxn
    )

    if out is None:
        return None

    sel, _rank = out
    enganche_final = float(sel["enganche_nuevo"])
    pct_enganche_final = float(sel["pct_enganche_nuevo"])
    credito_final = float(sel["credito_max"])
    tasa_m2 = (float(sel["tasa_anual_pct"]) / 100.0) / 12.0

    # -------------------------
    # Recalcular todo con nuevo enganche/crédito (Rescate)
    # -------------------------
    com_ap_final = round(credito_final * float(pol["comision_apertura_pct"]), 2)
    principal_resc = credito_final + (com_ap_final if pol.get("comision_apertura_financiada", True) else 0.0)
    if tipo == "apoyo":
        aplicar = min(subcuenta, principal_resc)
        principal_resc = max(0.0, principal_resc - aplicar)

    f2 = factor_anualidad(tasa_m2, plazo)
    cap_int2 = principal_resc * f2
    mensualidad2 = round(cap_int2 + seg_vida + seg_danos + com_admin, 2)
    ingreso_req2 = round(mensualidad2 * float(pol["relacion_ir"]), 2)

    # Desembolso nuevo
    descuento_sub_desembolso2 = 0.0
    if tipo in ("cta_infonavit", "fpt"):
        descuento_sub_desembolso2 = min(subcuenta, enganche_final)

    desembolso2 = round(enganche_final + avaluo + gastos_not + gastos_aprob, 2)
    if tipo == "cofinavit":
        desembolso2 = round(desembolso2 + round(credito_inst * float(pol.get("gastos_infonavit_pct", 0.0)), 2), 2)
    if tipo == "fpt":
        desembolso2 = round(desembolso2 + round(credito_inst * float(pol.get("gastos_fovissste_pct", 0.0)), 2), 2)
    desembolso2 = round(max(0.0, desembolso2 - descuento_sub_desembolso2), 2)

    pago_total_mens2 = round(mensualidad2 * plazo, 2)
    costo_total2 = round(desembolso2 + pago_total_mens2, 2)
    aforo_b2 = (credito_final / valor) if valor > 0 else 0.0
    aforo_i2 = (credito_inst / valor) if (valor > 0 and instituto_tiene_credito) else 0.0

    # Recalcular CAT
    cat_resc = cat_por_tir(
        credito_banorte=credito_final,
        avaluo=avaluo,
        gastos_aprob=gastos_aprob,
        com_apertura=com_ap_final,
        politicas=pol,
        mensualidad=mensualidad2,
        plazo=plazo
    )
    cat_resc_pct = (round(cat_resc*100, 1) if pd.notna(cat_resc) else np.nan)

    # Nota de enganche coherente
    if pct_enganche_final > pct_e_usado + 1e-9:
        nota_rescate = (
            f"Enganche aumentado de {pct_e_usado*100:.1f}% a "
            f"{pct_enganche_final*100:.1f}% para cumplir capacidad de pago."
        )
    elif abs(pct_enganche_final - pct_e_usado) <= 1e-9:
        nota_rescate = "Crédito ajustado para cumplir capacidad de pago (enganche sin cambio)."
    else:
        nota_rescate = "Parámetros ajustados para cumplir capacidad de pago."

    return {
        "modo": "Rescate",
        "producto": producto_cfg["nombre"],
        "tasa_nombre": sel["tasa_nombre"],
        "tasa_anual_pct": float(sel["tasa_anual_pct"]),
        "cat_pct": cat_resc_pct,
        "mensualidad": mensualidad2,
        "ingreso_req": ingreso_req2,
        "credito_banorte": round(credito_final, 2),
        "enganche": enganche_final,
        "pct_enganche": pct_enganche_final,
        "desembolso_inicial": desembolso2,
        "pago_total_mensualidades": pago_total_mens2,
        "costo_total_cliente": costo_total2,
        "plazo": plazo,
        "valor_vivienda": valor,
        "aforo_banorte_pct": round(aforo_b2*100, 2),
        "aforo_instituto_pct": round(aforo_i2*100, 2),
        "aforo_total_pct": round((aforo_b2+aforo_i2)*100, 2),
        "nota_enganche": nota_rescate,
    }


def generar_cotizaciones(productos, usuario, tol_mxn=50.0):
    """
    Recorre cada producto y cada tasa disponible, construye una cotización por tasa.
    Devuelve una lista de dicts (una cotización por tasa encontrada).
    """
    todas = []
    for cfg in productos:
        for tasa in cfg["tasas"]:
            nombre_tasa = tasa["nombre"]
            tasa_fija = tasa["tasa_anual_fija"]
            cot = _cotizar_por_tasa(cfg, usuario, nombre_tasa, tasa_fija, tol_mxn=tol_mxn)
            if cot is not None:
                todas.append(cot)
    return todas

# =====================================================
# Seccion 6: SALIDAS USUARIO Y BROKER (TODAS LAS COTIZACIONES)
# =====================================================

def salida_usuario_all(df_all: pd.DataFrame) -> pd.DataFrame:
    """
    Salida compacta para usuario final. Columnas (orden pensada para cliente):
    - Producto
    - Mensualidad
    - Pago inicial
    - Tasa
    - CAT
    - Crédito Banorte
    - Pago total
    """
    if df_all is None or df_all.empty:
        return df_all

    out = df_all.copy()

    # Formatos amigables
    out["Tasa"] = out["tasa_anual_pct"].map(lambda x: f"{x:.2f}%")
    out["CAT"] = out["cat_pct"].map(lambda x: ("ND" if pd.isna(x) else f"{x:.1f}%"))
    out["Crédito Banorte"] = out["credito_banorte"].map(money)
    out["Mensualidad"] = out["mensualidad"].map(money)
    out["Pago inicial"] = out["desembolso_inicial"].map(money)
    out["Pago total"] = out["costo_total_cliente"].map(money)

    out = out.rename(columns={"producto": "Producto"})

    cols = [
        "Producto",
        "Mensualidad",
        "Pago inicial",
        "Tasa",
        "CAT",
        "Crédito Banorte",
        "Pago total"
    ]
    return out[cols]

def salida_broker_all(df_all: pd.DataFrame) -> pd.DataFrame:
    """
    Salida robusta para broker (todos los campos relevantes de cada cotización).
    Incluye una fila por cada cotización (producto x tasa).
    Orden pensada para análisis rápido:
    - Identificación
    - Capacidad de pago
    - Estructura
    - Costos
    - Riesgo / notas
    """
    if df_all is None or df_all.empty:
        return df_all

    out = df_all.copy()

    # Formatos amigables
    out["Tasa"] = out["tasa_anual_pct"].map(lambda x: f"{x:.2f}%")
    out["CAT"] = out["cat_pct"].map(lambda x: ("ND" if pd.isna(x) else f"{x:.1f}%"))
    out["Mensualidad"] = out["mensualidad"].map(money)
    out["Ingreso requerido"] = out["ingreso_req"].map(money)
    out["Crédito Banorte"] = out["credito_banorte"].map(money)
    out["Enganche"] = out["enganche"].map(money)
    out["% Enganche"] = out["pct_enganche"].map(lambda x: f"{x*100:.2f}%")
    out["Pago inicial"] = out["desembolso_inicial"].map(money)
    out["Pago total mensualidades"] = out["pago_total_mensualidades"].map(money)
    out["Costo total"] = out["costo_total_cliente"].map(money)
    out["Aforo Banorte"] = out["aforo_banorte_pct"].map(lambda x: f"{x:.2f}%")
    out["Aforo Instituto"] = out["aforo_instituto_pct"].map(lambda x: f"{x:.2f}%")
    out["Aforo Total"] = out["aforo_total_pct"].map(lambda x: f"{x:.2f}%")

    ren = {
        "producto": "Producto",
        "tasa_nombre": "Nombre tasa",
        "plazo": "Plazo (meses)",
        "valor_vivienda": "Valor Vivienda"
    }
    out = out.rename(columns=ren)

    cols = [
        # Identificación
        "Producto", "Nombre tasa", "Tasa", "CAT", "modo",
        # Capacidad de pago
        "Mensualidad", "Ingreso requerido",
        # Estructura del financiamiento
        "Valor Vivienda", "Crédito Banorte", "Enganche", "% Enganche",
        "Aforo Banorte", "Aforo Instituto", "Aforo Total",
        # Costos
        "Pago inicial", "Pago total mensualidades", "Costo total",
        "Plazo (meses)",
        # Nota explicativa
        "nota_enganche"
    ]

    cols_final = [c for c in cols if c in out.columns]
    return out[cols_final]

# =====================================================
# Seccion 7: DEMO (USUARIO) Y EJECUCIÓN
# =====================================================

# -----------------------------------------------------
# Ordenador opcional de cotizaciones
# -----------------------------------------------------
def ordenar_cotizaciones(cotizaciones):
    """
    Ordena TODAS las cotizaciones por:
    1) mensualidad ascendente,
    2) tasa anual ascendente,
    3) costo total ascendente.
    Devuelve un DataFrame.
    """
    if not cotizaciones:
        return pd.DataFrame()
    df = pd.DataFrame(cotizaciones)
    df_sorted = df.sort_values(
        by=["mensualidad", "tasa_anual_pct", "costo_total_cliente"],
        ascending=[True, True, True]
    ).reset_index(drop=True)
    return df_sorted


# =====================================================
# ELECCIÓN DE PRODUCTOS SEGÚN EL PERFIL DEL USUARIO
# =====================================================

def productos_para_usuario(usuario: dict, productos_disponibles_db: list) -> list:
    """
    Filtra los productos que el banco ofrece según el perfil del usuario.
    Recibe:
    - usuario: El diccionario con los datos del cliente.
    - productos_disponibles_db: La lista de diccionarios (politicas_json) extraídos de la BD.
    """
    tiene_inf = bool(usuario.get("tiene_infonavit"))
    tiene_fov = bool(usuario.get("tiene_fovissste"))

    lista_productos = []

    for prod in productos_disponibles_db:
        tipo = prod.get("politicas", {}).get("tipo", "")
        
        # Regla 1: Todos pueden acceder al tradicional
        if tipo == "tradicional":
            lista_productos.append(prod)
            
        # Regla 2: Productos INFONAVIT
        elif tipo in ["apoyo", "cofinavit", "cta_infonavit"] and tiene_inf:
            lista_productos.append(prod)
            
        # Regla 3: Productos FOVISSSTE
        elif tipo == "fpt" and tiene_fov:
            lista_productos.append(prod)

    return lista_productos


# =====================================================
# USUARIO DE PRUEBA (CON INFONAVIT Y FOVISSSTE)
# =====================================================

USUARIO_DATOS = {
    "nombre": "Juan Pérez",
    "edad": 35,
    "sexo": "M",
    "ingreso_bruto": 40000.00,
    "valor_vivienda": 2_000_000.00,
    "pct_enganche": 0.10,
    "plazo_meses": 240,
    "tiene_infonavit": True,
    "tiene_fovissste": True,
    "infonavit": {
        "credito_infonavit": 561_419.81,
        "subcuenta_vivienda": 10_620.47
    },
    "fovissste": {
        "credito_fovissste": 1_018_841.88,
        "subcuenta_vivienda": 57_655.41
    }
}

RESULTADO_USUARIO_ALL = None     # ← aquí se guardarán los datos compactos
RESULTADO_BROKER_ALL  = None     # ← aquí se guardarán los datos detallados

# =====================================================
# FUNCIÓN PRINCIPAL DE EJECUCIÓN
# =====================================================

def ejecutar_escenario(usuario, titulo="ESCENARIO"):
    global RESULTADO_USUARIO_ALL, RESULTADO_BROKER_ALL

    print(f"\n========== {titulo}: {usuario.get('nombre','')} ==========\n")

    # 1) Elegir productos según el perfil del usuario
    productos_usuario = productos_para_usuario(usuario)

    # 2) Generar TODAS las cotizaciones (solo de esos productos)
    todas = generar_cotizaciones(productos_usuario, usuario, tol_mxn=50.0)

    if not todas:
        print("Sin cotizaciones viables para este perfil.")
        RESULTADO_USUARIO_ALL = pd.DataFrame()
        RESULTADO_BROKER_ALL  = pd.DataFrame()
        return

    # 3) Ordenar y armar salidas
    df_all = ordenar_cotizaciones(todas)

    # Salidas compacta (usuario) y detallada (broker)
    df_usuario = salida_usuario_all(df_all)
    df_broker = salida_broker_all(df_all)

    # Guardar en las variables globales
    RESULTADO_USUARIO_ALL = df_usuario.copy()
    RESULTADO_BROKER_ALL  = df_broker.copy()

    print("=== SALIDA USUARIO (TODAS LAS COTIZACIONES) ===")
    print(df_usuario.to_string(index=False))

    print("\n=== SALIDA BROKER (TODAS LAS COTIZACIONES) ===")
    print(df_broker.to_string(index=False))

# =====================================================
# FUNCIÓN MAESTRA PARA LA API
# =====================================================

def orquestar_cotizacion_banorte(datos_usuario: dict, productos_banco: list) -> dict:
    """
    Función puente entre FastAPI y las fórmulas de los Data Scientists.
    """
    # 1. Filtramos qué productos aplican
    productos_viables = productos_para_usuario(datos_usuario, productos_banco)
    
    # 2. Generamos las cotizaciones
    todas_las_cotizaciones = generar_cotizaciones(productos_viables, datos_usuario, tol_mxn=50.0)
    
    if not todas_las_cotizaciones:
        return {
            "exito": False,
            "mensaje": "No se encontraron cotizaciones viables para este perfil.",
            "data_usuario": [],
            "data_broker": []
        }
        
    # 3. Ordenamos usando la función que ellos crearon
    df_all = ordenar_cotizaciones(todas_las_cotizaciones)
    
    # 4. Formateamos usando las funciones que ellos crearon
    df_usuario = salida_usuario_all(df_all)
    df_broker = salida_broker_all(df_all)
    
    # Devolvemos un diccionario nativo de Python (FastAPI lo convertirá a JSON)
    return {
        "exito": True,
        "mensaje": "Cotizaciones generadas exitosamente.",
        "data_usuario": df_usuario.to_dict(orient="records"),
        "data_broker": df_broker.to_dict(orient="records")
    }