# Generated by Django 4.2.7 on 2026-03-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_key', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('tradicional', 'Tradicional'), ('apoyo', 'Apoyo INFONAVIT'), ('cofinavit', 'Cofinavit'), ('fpt', 'FPT (FOVISSSTE-Banorte)')], max_length=20)),
                ('max_ltv', models.DecimalField(decimal_places=4, max_digits=5)),
                ('income_payment_ratio', models.FloatField(default=2.0)),
                ('opening_commission_pct', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_commission_financed', models.BooleanField(default=True)),
                ('appraisal_pct_mil', models.DecimalField(decimal_places=4, default=0.0025, max_digits=5)),
                ('appraisal_fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notary_fees_pct', models.DecimalField(decimal_places=4, default=0.082, max_digits=5)),
                ('admin_fee_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_config', models.JSONField(help_text='Estructura de seguros de vida y daños')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mortgage_app.bank')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dti', models.FloatField(help_text='Debt-to-Income ratio')),
                ('delinq_2yrs', models.IntegerField(default=0)),
                ('inq_last_6mths', models.IntegerField(default=0)),
                ('open_acc', models.IntegerField()),
                ('pub_rec', models.IntegerField(default=0)),
                ('revol_bal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revol_util', models.FloatField()),
                ('total_acc', models.IntegerField()),
                ('earliest_cr_line_year', models.IntegerField()),
                ('tot_cur_bal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tot_coll_amt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_rev_hi_lim', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('home_ownership', models.CharField(choices=[('RENT', 'Renta'), ('OWN', 'Propia'), ('MORTGAGE', 'Hipotecada'), ('OTHER', 'Otro')], max_length=20)),
                ('verification_status', models.CharField(choices=[('not_verified', 'No Verificado'), ('source_verified', 'Fuente Verificada'), ('verified', 'Verificado')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('risk_label', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('annual_rate', models.DecimalField(decimal_places=5, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='mortgage_app.bankproduct')),
            ],
        ),
    ]
