# Generated by Django 4.2.7 on 2026-04-08 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('rfc_curp', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('nomina', 'Nómina'), ('independiente', 'Independiente'), ('publico', 'Público'), ('privado', 'Privado'), ('otro', 'Otro')], max_length=20, null=True)),
                ('job_seniority_years', models.IntegerField(default=0)),
                ('job_seniority_months', models.IntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_at_bank', models.BooleanField(default=False)),
                ('loan_amnt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_inc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('down_payment_pct', models.FloatField(default=10.0)),
                ('loan_term', models.IntegerField(blank=True, null=True)),
                ('property_location', models.CharField(blank=True, max_length=255, null=True)),
                ('financing_type', models.CharField(choices=[('infonavit', 'INFONAVIT'), ('fovissste', 'FOVISSSTE'), ('bancario', 'Bancario')], default='bancario', max_length=20)),
                ('institute_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('housing_subaccount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dti', models.FloatField(default=0.0)),
                ('delinq_2yrs', models.IntegerField(default=0)),
                ('inq_last_6mths', models.IntegerField(default=0)),
                ('open_acc', models.IntegerField(default=0)),
                ('pub_rec', models.IntegerField(default=0)),
                ('revol_bal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revol_util', models.FloatField(default=0.0)),
                ('total_acc', models.IntegerField(default=0)),
                ('earliest_cr_line_year', models.IntegerField(default=2000)),
                ('tot_cur_bal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tot_coll_amt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_rev_hi_lim', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('collections_12_mths_ex_med', models.IntegerField(default=0)),
                ('has_settlements', models.BooleanField(default=False)),
                ('settlement_count', models.IntegerField(default=0)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_recovery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('home_ownership', models.CharField(choices=[('RENT', 'Renta'), ('OWN', 'Propia'), ('MORTGAGE', 'Hipotecada'), ('OTHER', 'Otro'), ('ANY', 'Cualquiera'), ('NONE', 'Ninguno')], default='RENT', max_length=20)),
                ('verification_status', models.CharField(choices=[('not_verified', 'No Verificado'), ('source_verified', 'Fuente Verificada'), ('verified', 'Verificado')], default='not_verified', max_length=20)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_label', models.CharField(blank=True, max_length=50, null=True)),
                ('prob_low', models.FloatField(blank=True, null=True)),
                ('prob_medium', models.FloatField(blank=True, null=True)),
                ('prob_high', models.FloatField(blank=True, null=True)),
                ('recommendations_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_key', models.CharField(max_length=50, unique=True)),
                ('politicas_json', models.JSONField(help_text='Contiene toda la lógica: tasas, aforo, seguros, etc.')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mortgage_app.bank')),
            ],
        ),
    ]
