# Generated by Django 4.2.7 on 2026-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
