# Generated by Django 4.2.7 on 2026-05-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0002_loanapplication_first_name_loanapplication_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='municipality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Municipio'),
        ),
    ]
