# Generated by Django 4.2.7 on 2026-05-06 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mortgage_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0003_loanapplication_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Llenando Formulario'), ('sent_awaiting_ia', 'Enviado (Espera de IA)'), ('assigning_broker', 'Asignando Bróker'), ('broker_assigned', 'Bróker Asignado'), ('reviewing_quote', 'Revisando Cotización (Bróker)'), ('quote_approved', 'Cotización Aprobada'), ('quote_rejected_broker', 'Rechazada por Bróker'), ('waiting_client_approval', 'En espera de aceptación del cliente'), ('quote_rejected_client', 'Cotización rechazada por cliente'), ('waiting_docs', 'En espera de documentos'), ('docs_review', 'Revisando documentos'), ('docs_approved', 'Documentos aprobados'), ('waiting_appointment', 'En espera de agendamiento'), ('appointment_scheduled', 'Cita agendada'), ('finished', 'Proceso finalizado')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identificacion', 'Identificación Oficial'), ('domicilio', 'Comprobante de Domicilio'), ('ingresos', 'Comprobante de Ingresos'), ('fiscal', 'Constancia de Situación Fiscal'), ('buro', 'Reporte de Buró de Crédito')], max_length=20)),
                ('file', models.FileField(upload_to=mortgage_app.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=15)),
                ('feedback', models.TextField(blank=True, help_text='Razón del rechazo', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mortgage_app.loanapplication')),
            ],
            options={
                'verbose_name': 'Documentos del Cliente',
                'unique_together': {('application', 'document_type', 'status')},
            },
        ),
    ]
