# Generated by Django 4.2.7 on 2026-05-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0004_alter_loanapplication_status_customerdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdocument',
            options={'verbose_name': 'Documento del Cliente', 'verbose_name_plural': 'Documentos del Cliente'},
        ),
        migrations.AlterUniqueTogether(
            name='customerdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='assigned_broker_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Bróker asignado'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Llenando Formulario'), ('sent_awaiting_ia', 'Enviado (Espera de IA)'), ('assigning_broker', 'Asignando Bróker'), ('broker_assigned', 'Bróker Asignado'), ('reviewing_quote', 'Revisando Cotización (Bróker)'), ('quote_approved', 'Cotización Aprobada'), ('quote_rejected_broker', 'Rechazada por Bróker'), ('waiting_client_approval', 'En espera de aceptación del cliente'), ('quote_rejected_client', 'Cotización rechazada por cliente'), ('waiting_docs', 'En espera de documentos'), ('docs_review', 'Revisando documentos'), ('docs_approved', 'Documentos aprobados'), ('waiting_appointment', 'En espera de agendamiento'), ('appointment_scheduled', 'Cita agendada'), ('finished', 'Proceso finalizado'), ('invalid_data', ''), ('error_intelligence', '')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
