# Generated by Django 4.2.7 on 2026-05-09 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0005_alter_customerdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='declined_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Lista de IDs de brókers que rechazaron la solicitud', size=None),
        ),
    ]
