# Generated by Django 4.2.7 on 2026-05-10 00:15

import django.core.validators
from django.db import migrations, models
import mortgage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0006_loanapplication_declined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mortgage_app.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='status',
            field=models.CharField(choices=[('requested', 'Requerido'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='requested', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='customerdocument',
            unique_together={('application', 'document_type')},
        ),
    ]
