# Generated by Django 4.2.7 on 2026-05-11 01:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0008_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duración de la cita. Mínimo 15 mins, Máximo 3 horas.', null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('physical', 'Presencial (Sucursal/Oficina)'), ('virtual', 'Virtual (Videollamada)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='mortgage_app.loanapplication'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(help_text='Dirección física o URL de Zoom/Meet/Teams', max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_client', 'Esperando selección del cliente'), ('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending_client', max_length=20),
        ),
    ]
