# Generated by Django 4.2.7 on 2026-05-11 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mortgage_app', '0009_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha en la que el bróker está disponible')),
                ('start_time', models.TimeField(help_text='Hora de inicio del turno')),
                ('end_time', models.TimeField(help_text='Hora de fin del turno')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Bróker',
                'verbose_name_plural': 'Disponibilidades de Bróker',
                'unique_together': {('broker', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
