# Generated by Django 4.2.7 on 2026-05-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0010_brokeravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brokeravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brokeravailability',
            name='broker_user_id',
            field=models.IntegerField(db_index=True, default=0, help_text='ID del bróker (Microservicio Identity)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='brokeravailability',
            unique_together={('broker_user_id', 'date', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='brokeravailability',
            name='broker',
        ),
    ]
