# Generated by Django 4.2.7 on 2026-05-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0011_alter_brokeravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='selected_quotes',
            field=models.JSONField(blank=True, help_text='Arreglo de JSONs con las cotizaciones elegidas por el bróker para enviarle al cliente.', null=True),
        ),
    ]
